sudo: required
service:
  - docker

berfore_install:
  - docker build -t sandrobrayen/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true sandrobrayen/docker-react npm run test -- --coverage